server:
  port: 9081

spring:
  application:
    name: fraud-verifier

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
