server:
  port: 9083
spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
      - id: fraud
        uri: lb://fraud-verifier
        predicates:
        - Path=/fraud-verifier/**
        filters:
        - StripPrefix=1
        - name: Retry
          args:
            retries: 3
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health