server:
  port: 9888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/spring-cloud-intro-demo-config

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health